backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "reviews"
    label: "Recenzii"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titlu"
        name: "title"
        widget: "string"
      - label: "Autor"
        name: "author"
        widget: "string"
        required: false
      - label: "Imagine"
        name: "image"
        widget: "image"
        required: false
      - label: "Link video (YouTube)"
        name: "video"
        widget: "string"
        required: false
      - label: "Textul recenziei"
        name: "body"
        widget: "markdown"
        required: false
